# Generated by Django 2.2.1 on 2019-05-11 00:10

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Angel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_home', models.TextField(blank=True, default='', verbose_name='מידע על הבית')),
                ('full_name', models.CharField(max_length=200, verbose_name='שם מלא')),
                ('email', models.EmailField(max_length=254, verbose_name='כתובת דואר אלקטרוני')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='טלפון')),
                ('call_at_night', models.BooleanField(default=False, verbose_name='אתם יכולים להתקשר אלי אחרי 22:00 אם יש צורך באומנה')),
                ('address', models.CharField(max_length=200, verbose_name='כתובת בבית')),
                ('dob', models.DateField(verbose_name='תאריך לידה')),
                ('comment', models.TextField(blank=True, default='', verbose_name='מידע נוסף')),
                ('admin_comment', models.TextField(blank=True, default='', verbose_name='הערות מנהלים')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='תאריך הרשמה')),
                ('foster_at_home', models.BooleanField(blank=True, default=False, verbose_name='מגורים בבית')),
                ('home_with_garden', models.BooleanField(blank=True, default=False, verbose_name='יש גינה')),
                ('have_car', models.BooleanField(blank=True, default=False, verbose_name='יש רכב')),
                ('can_pay_food', models.BooleanField(blank=True, default=False, verbose_name='יכולים לשלם על אוכל')),
                ('can_pay_medicine', models.BooleanField(blank=True, default=False, verbose_name='יכולים לשלם על תרופות וטיפולים')),
                ('can_handle_sick', models.BooleanField(blank=True, default=False, verbose_name='יכולים לטפל בבע"ח פצועים או חולים')),
                ('can_handle_bad_behaviour', models.BooleanField(blank=True, default=False, verbose_name='יכולים לטפל בבעיות התנהגות (לא בעלי חיים אגרסיביים)')),
                ('can_handle_aggressive', models.BooleanField(blank=True, default=False, verbose_name='יכולים לטפל בבעלי חיים אגרסיבים')),
                ('animals', multiselectfield.db.fields.MultiSelectField(choices=[('puppy', 'Puppy'), ('dog', 'Dog'), ('senior_dog', 'Senior Dog'), ('kittens', 'Kittens'), ('cat', 'Cat'), ('senior_cat', 'Senior Cat')], max_length=43)),
                ('agree_to_no_time_limit', models.BooleanField(verbose_name='אני מודע/ת לכך שהאומנה היא ללא מגבלת זמן')),
                ('agree_to_no_transfer', models.BooleanField(verbose_name='אני מודע/ת לכך שאני לא אוכל למסור את האומנה ללא אישור דימונה אוהבת חיות')),
                ('agree_to_pay', models.BooleanField(verbose_name='אני מודע/ת לכך שאני אצטרך לשלם על כל הצרכים של האומנה אלא אם דימונה אוהבת חיות תשתתף')),
                ('agree_to_week', models.BooleanField(verbose_name='אני מודע/ת לכך שאני לא יכול/ה לסיים את האומנה ללא הודעה מראש של לפחות שבוע לדימונה אוהבת חיות')),
                ('agree_to_take', models.BooleanField(verbose_name='אני מודע/ת לכך שאני אצטרף לקחת את האומנה לכל מקום שנדרש בעצמי')),
                ('agree_to_photo', models.BooleanField(verbose_name='אני מודע/ת לכך שאני אצטרך לספק תמונות של האומנה לדימונה אוהבת חיות')),
                ('agree_to_bring', models.BooleanField(verbose_name='אני מודע/ת לכך שאני אצטרך להביא את האומנה לימי אימוץ כנדרש')),
                ('accept_terms', models.BooleanField(verbose_name='אני מאשר/ת את התנאים')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Foster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='starting date')),
                ('end_date', models.DateTimeField(verbose_name='ending date')),
                ('comment', models.CharField(max_length=200)),
                ('done', models.BooleanField(default=False)),
                ('angel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foster.Angel')),
            ],
        ),
    ]
